import React, { Fragment, useState } from "react";
// import { withStyles } from "@material-ui/core/styles";
// import AppBar from "@material-ui/core/AppBar";
// import Toolbar from "@material-ui/core/Toolbar";
import Typography from "react";
// import MenuItem from "@material-ui/core/MenuItem";
import Grid from "react";
// import IconButton from "@material-ui/core/IconButton";
import ChangeIcon from "react";
import ArrowIcon from "react";
import Toast from "./Toast";
import { Button } from "@/components/ui/button"

// const styles = theme => ({
//   paper: {
//     ...theme.mixins.gutters(),
//     paddingTop: theme.spacing.unit * 2,
//     paddingBottom: theme.spacing.unit * 2
//   },
//   container: {
//     display: "flex",
//     justifyContent: "center",
//     alignItems: "center",
//     height: "calc(100vh - 64px)"
//   },
//   textField: {
//     marginLeft: theme.spacing.unit,
//     marginRight: theme.spacing.unit,
//     width: 200
//   },
//   button: {
//     display: "flex",
//     justifyContent: "center"
//   },
//   body2Bold: {
//     fontWeight: "bold"
//   },
//   good: {
//     color: "green"
//   },
//   acc: {
//     color: "#828e24"
//   },
//   bad: {
//     color: "red"
//   },
//   margin: {
//     marginBottom: 24
//   }
// });

const currencies = [
  { currencyName: "British Pound", currencySymbol: "\u00a3", id: "GBP" },
  { currencyName: "United States Dollar", currencySymbol: "$", id: "USD" },
  { currencyName: "Euro", currencySymbol: "\u20ac", id: "EUR" },
  { currencyName: "Canadian Dollar", currencySymbol: "$", id: "CAD" },
  { currencyName: "Japanese Yen", currencySymbol: "\u00a5", id: "JPY" },
  { currencyName: "Albanian Lek", currencySymbol: "Lek", id: "ALL" },
  { currencyName: "East Caribbean Dollar", currencySymbol: "$", id: "XCD" },
  { currencyName: "Barbadian Dollar", currencySymbol: "$", id: "BBD" },
  { currencyName: "Bhutanese Ngultrum", id: "BTN" },
  { currencyName: "Brunei Dollar", currencySymbol: "$", id: "BND" },
  { currencyName: "Central African CFA Franc", id: "XAF" },
  { currencyName: "Cuban Peso", currencySymbol: "$", id: "CUP" },
  { currencyName: "Falkland Islands Pound", currencySymbol: "\u00a3", id: "FKP" },
  { currencyName: "Gibraltar Pound", currencySymbol: "\u00a3", id: "GIP" },
  { currencyName: "Hungarian Forint", currencySymbol: "Ft", id: "HUF" },
  { currencyName: "Iranian Rial", currencySymbol: "\ufdfc", id: "IRR" },
  { currencyName: "Jamaican Dollar", currencySymbol: "J$", id: "JMD" },
  { currencyName: "Australian Dollar", currencySymbol: "$", id: "AUD" },
  { currencyName: "Lao Kip", currencySymbol: "\u20ad", id: "LAK" },
  { currencyName: "Libyan Dinar", id: "LYD" },
  { currencyName: "Macedonian Denar", currencySymbol: "\u0434\u0435\u043d", id: "MKD" },
  { currencyName: "West African CFA Franc", id: "XOF" },
  { currencyName: "New Zealand Dollar", currencySymbol: "$", id: "NZD" },
  { currencyName: "Omani Rial", currencySymbol: "\ufdfc", id: "OMR" },
  { currencyName: "Papua New Guinean Kina", id: "PGK" },
  { currencyName: "Rwandan Franc", id: "RWF" },
  { currencyName: "Samoan Tala", id: "WST" },
  { currencyName: "Serbian Dinar", currencySymbol: "\u0414\u0438\u043d.", id: "RSD" },
  { currencyName: "Swedish Krona", currencySymbol: "kr", id: "SEK" },
  { currencyName: "Tanzanian Shilling", currencySymbol: "TSh", id: "TZS" },
  { currencyName: "Armenian Dram", id: "AMD" },
  { currencyName: "Bahamian Dollar", currencySymbol: "$", id: "BSD" },
  { currencyName: "Bosnia And Herzegovina Konvertibilna Marka", currencySymbol: "KM", id: "BAM" },
  { currencyName: "Cape Verdean Escudo", id: "CVE" },
  { currencyName: "Chinese Yuan", currencySymbol: "\u00a5", id: "CNY" },
  { currencyName: "Costa Rican Colon", currencySymbol: "\u20a1", id: "CRC" },
  { currencyName: "Czech Koruna", currencySymbol: "K\u010d", id: "CZK" },
  { currencyName: "Eritrean Nakfa", id: "ERN" },
  { currencyName: "Georgian Lari", id: "GEL" },
  { currencyName: "Haitian Gourde", id: "HTG" },
  { currencyName: "Indian Rupee", currencySymbol: "\u20b9", id: "INR" },
  { currencyName: "Jordanian Dinar", id: "JOD" },
  { currencyName: "South Korean Won", currencySymbol: "\u20a9", id: "KRW" },
  { currencyName: "Lebanese Lira", currencySymbol: "\u00a3", id: "LBP" },
  { currencyName: "Malawian Kwacha", id: "MWK" },
  { currencyName: "Mauritanian Ouguiya", id: "MRO" },
  { currencyName: "Mozambican Metical", id: "MZN" },
  { currencyName: "Netherlands Antillean Gulden", currencySymbol: "\u0192", id: "ANG" },
  { currencyName: "Peruvian Nuevo Sol", currencySymbol: "S/.", id: "PEN" },
  { currencyName: "Qatari Riyal", currencySymbol: "\ufdfc", id: "QAR" },
  { currencyName: "Sao Tome And Principe Dobra", id: "STD" },
  { currencyName: "Sierra Leonean Leone", id: "SLL" },
  { currencyName: "Somali Shilling", currencySymbol: "S", id: "SOS" },
  { currencyName: "Sudanese Pound", id: "SDG" },
  { currencyName: "Syrian Pound", currencySymbol: "\u00a3", id: "SYP" },
  { currencyName: "Angolan Kwanza", id: "AOA" },
  { currencyName: "Aruban Florin", currencySymbol: "\u0192", id: "AWG" },
  { currencyName: "Bahraini Dinar", id: "BHD" },
  { currencyName: "Belize Dollar", currencySymbol: "BZ$", id: "BZD" },
  { currencyName: "Botswana Pula", currencySymbol: "P", id: "BWP" },
  { currencyName: "Burundi Franc", id: "BIF" },
  { currencyName: "Cayman Islands Dollar", currencySymbol: "$", id: "KYD" },
  { currencyName: "Colombian Peso", currencySymbol: "$", id: "COP" },
  { currencyName: "Danish Krone", currencySymbol: "kr", id: "DKK" },
  { currencyName: "Guatemalan Quetzal", currencySymbol: "Q", id: "GTQ" },
  { currencyName: "Honduran Lempira", currencySymbol: "L", id: "HNL" },
  { currencyName: "Indonesian Rupiah", currencySymbol: "Rp", id: "IDR" },
  { currencyName: "Israeli New Sheqel", currencySymbol: "\u20aa", id: "ILS" },
  { currencyName: "Kazakhstani Tenge", currencySymbol: "\u043b\u0432", id: "KZT" },
  { currencyName: "Kuwaiti Dinar", id: "KWD" },
  { currencyName: "Lesotho Loti", id: "LSL" },
  { currencyName: "Malaysian Ringgit", currencySymbol: "RM", id: "MYR" },
  { currencyName: "Mauritian Rupee", currencySymbol: "\u20a8", id: "MUR" },
  { currencyName: "Mongolian Tugrik", currencySymbol: "\u20ae", id: "MNT" },
  { currencyName: "Myanma Kyat", id: "MMK" },
  { currencyName: "Nigerian Naira", currencySymbol: "\u20a6", id: "NGN" },
  { currencyName: "Panamanian Balboa", currencySymbol: "B/.", id: "PAB" },
  { currencyName: "Philippine Peso", currencySymbol: "\u20b1", id: "PHP" },
  { currencyName: "Romanian Leu", currencySymbol: "lei", id: "RON" },
  { currencyName: "Saudi Riyal", currencySymbol: "\ufdfc", id: "SAR" },
  { currencyName: "Singapore Dollar", currencySymbol: "$", id: "SGD" },
  { currencyName: "South African Rand", currencySymbol: "R", id: "ZAR" },
  { currencyName: "Surinamese Dollar", currencySymbol: "$", id: "SRD" },
  { currencyName: "New Taiwan Dollar", currencySymbol: "NT$", id: "TWD" },
  { currencyName: "Paanga", id: "TOP" },
  { currencyName: "Venezuelan Bolivar", id: "VEF" },
  { currencyName: "Algerian Dinar", id: "DZD" },
  { currencyName: "Argentine Peso", currencySymbol: "$", id: "ARS" },
  { currencyName: "Azerbaijani Manat", currencySymbol: "\u043c\u0430\u043d", id: "AZN" },
  { currencyName: "Belarusian Ruble", currencySymbol: "p.", id: "BYR" },
  { currencyName: "Bolivian Boliviano", currencySymbol: "$b", id: "BOB" },
  { currencyName: "Bulgarian Lev", currencySymbol: "\u043b\u0432", id: "BGN" },
  { currencyName: "Chilean Peso", currencySymbol: "$", id: "CLP" },
  { currencyName: "Congolese Franc", id: "CDF" },
  { currencyName: "Dominican Peso", currencySymbol: "RD$", id: "DOP" },
  { currencyName: "Fijian Dollar", currencySymbol: "$", id: "FJD" },
  { currencyName: "Gambian Dalasi", id: "GMD" },
  { currencyName: "Guyanese Dollar", currencySymbol: "$", id: "GYD" },
  { currencyName: "Icelandic Kr\u00f3na", currencySymbol: "kr", id: "ISK" },
  { currencyName: "Iraqi Dinar", id: "IQD" },
  const currencies = [
  { currencyName: "British Pound", currencySymbol: "\u00a3", id: "GBP" },
  { currencyName: "United States Dollar", currencySymbol: "$", id: "USD" },
  { currencyName: "Euro", currencySymbol: "\u20ac", id: "EUR" },
  { currencyName: "Canadian Dollar", currencySymbol: "$", id: "CAD" },
  { currencyName: "Japanese Yen", currencySymbol: "\u00a5", id: "JPY" },
  { currencyName: "Albanian Lek", currencySymbol: "Lek", id: "ALL" },
  { currencyName: "East Caribbean Dollar", currencySymbol: "$", id: "XCD" },
  { currencyName: "Barbadian Dollar", currencySymbol: "$", id: "BBD" },
  { currencyName: "Bhutanese Ngultrum", id: "BTN" },
  { currencyName: "Brunei Dollar", currencySymbol: "$", id: "BND" },
  { currencyName: "Central African CFA Franc", id: "XAF" },
  { currencyName: "Cuban Peso", currencySymbol: "$", id: "CUP" },
  { currencyName: "Falkland Islands Pound", currencySymbol: "\u00a3", id: "FKP" },
  { currencyName: "Gibraltar Pound", currencySymbol: "\u00a3", id: "GIP" },
  { currencyName: "Hungarian Forint", currencySymbol: "Ft", id: "HUF" },
  { currencyName: "Iranian Rial", currencySymbol: "\ufdfc", id: "IRR" },
  { currencyName: "Jamaican Dollar", currencySymbol: "J$", id: "JMD" },
  { currencyName: "Australian Dollar", currencySymbol: "$", id: "AUD" },
  { currencyName: "Lao Kip", currencySymbol: "\u20ad", id: "LAK" },
  { currencyName: "Libyan Dinar", id: "LYD" },
  { currencyName: "Macedonian Denar", currencySymbol: "\u0434\u0435\u043d", id: "MKD" },
  { currencyName: "West African CFA Franc", id: "XOF" },
  { currencyName: "New Zealand Dollar", currencySymbol: "$", id: "NZD" },
  { currencyName: "Omani Rial", currencySymbol: "\ufdfc", id: "OMR" },
  { currencyName: "Papua New Guinean Kina", id: "PGK" },
  { currencyName: "Rwandan Franc", id: "RWF" },
  { currencyName: "Samoan Tala", id: "WST" },
  { currencyName: "Serbian Dinar", currencySymbol: "\u0414\u0438\u043d.", id: "RSD" },
  { currencyName: "Swedish Krona", currencySymbol: "kr", id: "SEK" },
  { currencyName: "Tanzanian Shilling", currencySymbol: "TSh", id: "TZS" },
  { currencyName: "Armenian Dram", id: "AMD" },
  { currencyName: "Bahamian Dollar", currencySymbol: "$", id: "BSD" },
  { currencyName: "Bosnia And Herzegovina Konvertibilna Marka", currencySymbol: "KM", id: "BAM" },
  { currencyName: "Cape Verdean Escudo", id: "CVE" },
  { currencyName: "Chinese Yuan", currencySymbol: "\u00a5", id: "CNY" },
  { currencyName: "Costa Rican Colon", currencySymbol: "\u20a1", id: "CRC" },
  { currencyName: "Czech Koruna", currencySymbol: "K\u010d", id: "CZK" },
  { currencyName: "Eritrean Nakfa", id: "ERN" },
  { currencyName: "Georgian Lari", id: "GEL" },
  { currencyName: "Haitian Gourde", id: "HTG" },
  { currencyName: "Indian Rupee", currencySymbol: "\u20b9", id: "INR" },
  { currencyName: "Jordanian Dinar", id: "JOD" },
  { currencyName: "South Korean Won", currencySymbol: "\u20a9", id: "KRW" },
  { currencyName: "Lebanese Lira", currencySymbol: "\u00a3", id: "LBP" },
  { currencyName: "Malawian Kwacha", id: "MWK" },
  { currencyName: "Mauritanian Ouguiya", id: "MRO" },
  { currencyName: "Mozambican Metical", id: "MZN" },
  { currencyName: "Netherlands Antillean Gulden", currencySymbol: "\u0192", id: "ANG" },
  { currencyName: "Peruvian Nuevo Sol", currencySymbol: "S/.", id: "PEN" },
  { currencyName: "Qatari Riyal", currencySymbol: "\ufdfc", id: "QAR" },
  { currencyName: "Sao Tome And Principe Dobra", id: "STD" },
  { currencyName: "Sierra Leonean Leone", id: "SLL" },
  { currencyName: "Somali Shilling", currencySymbol: "S", id: "SOS" },
  { currencyName: "Sudanese Pound", id: "SDG" },
  { currencyName: "Syrian Pound", currencySymbol: "\u00a3", id: "SYP" },
  { currencyName: "Angolan Kwanza", id: "AOA" },
  { currencyName: "Aruban Florin", currencySymbol: "\u0192", id: "AWG" },
  { currencyName: "Bahraini Dinar", id: "BHD" },
  { currencyName: "Belize Dollar", currencySymbol: "BZ$", id: "BZD" },
  { currencyName: "Botswana Pula", currencySymbol: "P", id: "BWP" },
  { currencyName: "Burundi Franc", id: "BIF" },
  { currencyName: "Cayman Islands Dollar", currencySymbol: "$", id: "KYD" },
  { currencyName: "Colombian Peso", currencySymbol: "$", id: "COP" },
  { currencyName: "Danish Krone", currencySymbol: "kr", id: "DKK" },
  { currencyName: "Guatemalan Quetzal", currencySymbol: "Q", id: "GTQ" },
  { currencyName: "Honduran Lempira", currencySymbol: "L", id: "HNL" },
  { currencyName: "Indonesian Rupiah", currencySymbol: "Rp", id: "IDR" },
  { currencyName: "Israeli New Sheqel", currencySymbol: "\u20aa", id: "ILS" },
  { currencyName: "Kazakhstani Tenge", currencySymbol: "\u043b\u0432", id: "KZT" },
  { currencyName: "Kuwaiti Dinar", id: "KWD" },
  { currencyName: "Lesotho Loti", id: "LSL" },
  { currencyName: "Malaysian Ringgit", currencySymbol: "RM", id: "MYR" },
  { currencyName: "Mauritian Rupee", currencySymbol: "\u20a8", id: "MUR" },
  { currencyName: "Mongolian Tugrik", currencySymbol: "\u20ae", id: "MNT" },
  { currencyName: "Myanma Kyat", id: "MMK" },
  { currencyName: "Nigerian Naira", currencySymbol: "\u20a6", id: "NGN" },
  { currencyName: "Panamanian Balboa", currencySymbol: "B/.", id: "PAB" },
  { currencyName: "Philippine Peso", currencySymbol: "\u20b1", id: "PHP" },
  { currencyName: "Romanian Leu", currencySymbol: "lei", id: "RON" },
  { currencyName: "Saudi Riyal", currencySymbol: "\ufdfc", id: "SAR" },
  { currencyName: "Singapore Dollar", currencySymbol: "$", id: "SGD" },
  { currencyName: "South African Rand", currencySymbol: "R", id: "ZAR" },
  { currencyName: "Surinamese Dollar", currencySymbol: "$", id: "SRD" },
  { currencyName: "New Taiwan Dollar", currencySymbol: "NT$", id: "TWD" },
  { currencyName: "Paanga", id: "TOP" },
  { currencyName: "Venezuelan Bolivar", id: "VEF" },
  { currencyName: "Algerian Dinar", id: "DZD" },
  { currencyName: "Argentine Peso", currencySymbol: "$", id: "ARS" },
  { currencyName: "Azerbaijani Manat", currencySymbol: "\u043c\u0430\u043d", id: "AZN" },
  { currencyName: "Belarusian Ruble", currencySymbol: "p.", id: "BYR" },
  { currencyName: "Bolivian Boliviano", currencySymbol: "$b", id: "BOB" },
  { currencyName: "Bulgarian Lev", currencySymbol: "\u043b\u0432", id: "BGN" },
  { currencyName: "Chilean Peso", currencySymbol: "$", id: "CLP" },
  { currencyName: "Congolese Franc", id: "CDF" },
  { currencyName: "Dominican Peso", currencySymbol: "RD$", id: "DOP" },
  { currencyName: "Fijian Dollar", currencySymbol: "$", id: "FJD" },
  { currencyName: "Gambian Dalasi", id: "GMD" },
  { currencyName: "Guyanese Dollar", currencySymbol: "$", id: "GYD" },
  { currencyName: "Icelandic Kr\u00f3na", currencySymbol: "kr", id: "ISK" },
  { currencyName: "Iraqi Dinar", id: "IQD" },
